image: node:4.6.0
pipelines:
   default:
      - step:
         caches:
            - node
         script:
            - npm install
            - npm install gulp-cli -g
            - npm install gulp -D
            - gulp build site
   branches:
      release:
         - step:
            caches:
               - node
            script:
               - npm install
               - npm install gulp-cli -g
               - npm install gulp -D
               - gulp build site
               - printf "//`node -p \"require('url').parse(process.env.NPM_REGISTRY_URL || 'https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc
               - git config user.email "francois.achache@gmail.com"
               - git config user.name "hhfrancois"
               - git add dist/bootstrap-csstree.css
               - npm version patch
               - git push origin $BITBUCKET_BRANCH:master
               - git push origin --tags
               - npm publish
